---
#- hosts: testserver
- hosts: 127.0.0.1
  remote_user: root
  tasks:
  #############################################################################################################
  #                                         Tear down fluentd service 
  #############################################################################################################
  - name: remove td-agent
    action: yum pkg=td-agent state=removed
  #############################################################################################################
  #                                        End tear down fluentd service 
  #############################################################################################################

  #############################################################################################################
  #                                          Tear down fluentd service 
  #############################################################################################################
  - name: run logstash
    action: yum pkg=logstash state=removed
  #############################################################################################################
  #                                        End tear down fluentd service 
  #############################################################################################################

  #############################################################################################################
  #                                          Tear down kibana service 
  # Can't completely remove kibana, because you can never install it again and hav it run.  There seems to 
  # be a bug that pops up if you reinstall.                                         
  #############################################################################################################
  - name: run kibana
    service: name=kibana state=stopped enabled=no
  #############################################################################################################
  #                                        End tear down kibana service 
  #############################################################################################################

  #############################################################################################################
  #                                        Tear down Elasticsearch service 
  #############################################################################################################
  - name: remove node1_elasticsearch
    action: yum pkg=node1_elasticsearch state=removed

  - name: remove elasticsearch
    action: yum pkg=elasticsearch state=removed

  - name: remove elasticsearch role
    shell: 'rm -rf /etc/ansible/roles/elastic.elasticsearch'
  #############################################################################################################
  #                                       End tear down Elasticsearch service 
  #############################################################################################################
